# Generated by Django 5.2.17 on 2026-09-02 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=240, unique=True),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
