# Generated by Django 5.2.17 on 2026-09-02 19:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_alter_brand_slug_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('base_url', models.URLField(blank=True)),
                ('allowed_image_domains', models.JSONField(blank=True, default=list)),
                ('percentage_margin', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('fixed_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('rounding_rule', models.CharField(default='NONE', max_length=20)),
                ('minimum_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='source_type',
            field=models.CharField(choices=[('DEMO', 'Demo'), ('MANUAL', 'Manuel'), ('EXCEL', 'Import Excel/CSV'), ('SUPPLIER', 'Fournisseur')], db_index=True, default='MANUAL', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PREVIEWED', 'Previsualise'), ('COMPLETED', 'Termine'), ('FAILED', 'Echec')], default='PREVIEWED', max_length=20)),
                ('update_existing', models.BooleanField(default=False)),
                ('create_missing_relations', models.BooleanField(default=True)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error_report', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.PositiveIntegerField()),
                ('raw_data', models.JSONField(default=dict)),
                ('normalized_data', models.JSONField(blank=True, default=dict)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('duplicate_sku', models.BooleanField(default=False)),
                ('imported_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.product')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='commerce.productimportjob')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_product_id', models.CharField(max_length=160)),
                ('source_url', models.URLField(blank=True)),
                ('source_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('source_stock', models.IntegerField(blank=True, null=True)),
                ('last_synchronized_at', models.DateTimeField(blank=True, null=True)),
                ('synchronization_status', models.CharField(choices=[('IMPORTED', 'Importe'), ('NEEDS_REVIEW', 'A verifier'), ('APPROVED', 'Approuve'), ('PUBLISHED', 'Publie'), ('REJECTED', 'Rejete'), ('ERROR', 'Erreur')], default='IMPORTED', max_length=30)),
                ('synchronization_error', models.TextField(blank=True)),
                ('applied_margin', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('final_selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('manual_price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('local_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_records', to='commerce.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_products', to='commerce.supplier')),
            ],
            options={
                'unique_together': {('supplier', 'external_product_id')},
            },
        ),
    ]
