# Generated by Django 5.2.17 on 2026-09-13 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def add_order_idempotency_key_if_missing(apps, schema_editor):
    Order = apps.get_model("commerce", "Order")
    table = Order._meta.db_table
    columns = {column.name for column in schema_editor.connection.introspection.get_table_description(schema_editor.connection.cursor(), table)}
    if "idempotency_key" in columns:
        return
    field = models.CharField(blank=True, db_index=True, max_length=80, null=True, unique=True)
    field.set_attributes_from_name("idempotency_key")
    schema_editor.add_field(Order, field)


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_couponusage_guest_email_order_guest_email_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunPython(add_order_idempotency_key_if_missing, migrations.RunPython.noop)],
            state_operations=[
                migrations.AddField(
                    model_name='order',
                    name='idempotency_key',
                    field=models.CharField(blank=True, db_index=True, max_length=80, null=True, unique=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='admin_decision',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Accepte'), ('REJECTED', 'Rejete'), ('REPLACED', 'Remplace'), ('REFUNDED', 'Rembourse')], default='PENDING', max_length=30),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(db_index=True, max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(db_index=True)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='expenses/')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='commerce.supplier')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(max_length=80)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuve'), ('REJECTED', 'Rejete'), ('PAID', 'Verse')], default='PENDING', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='commerce.order')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReturnHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='commerce.returnrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
