# Generated by Django 5.2.17 on 2026-09-19 13:56

from django.db import migrations, models


def seed_home_sections(apps, schema_editor):
    HomeSection = apps.get_model('commerce', 'HomeSection')
    defaults = [
        ('popular-products', 'Produits populaires', 'Selection manuelle de produits a mettre en avant.', 10),
        ('new-arrivals', 'Nouveautes', 'Produits recemment choisis pour la page d accueil.', 20),
        ('best-sellers', 'Meilleures ventes', 'Produits que vous voulez presenter comme meilleures ventes.', 30),
        ('promotions', 'Promotions', 'Produits en promotion visibles sur la page d accueil.', 40),
    ]
    for key, title, description, display_order in defaults:
        HomeSection.objects.get_or_create(
            key=key,
            defaults={
                'title': title,
                'description': description,
                'display_order': display_order,
                'is_visible': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_alter_cartitem_unique_together_cartitem_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=140)),
                ('description', models.CharField(blank=True, max_length=260)),
                ('is_visible', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('products', models.ManyToManyField(blank=True, related_name='home_sections', to='commerce.product')),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.RunPython(seed_home_sections, migrations.RunPython.noop),
    ]
