# Generated by Django 5.2.17 on 2026-09-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_homesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='page_permissions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
